version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: "true"
      DB_HOST: "postgres"
    hostname: "web"
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "0324B0324l!"
    ports:
      - "5432:5432"